### ISSUE TITLE
hicmaptools -sites options

### ISSUE THREAD

**Issue by Lucas446** [changlabtw/hicmaptools#8] opened 2024-01-22 22:49 UTC
Hi, 

I would like to calculate the interaction between all the possible pairs from a list of region in a bed file: chr start end

I use the following command:

`hicmaptools -in_hic ${m} -in_hic_norm KR -in_hic_resol 25000 -sites ${bed} -random 1000 -output ${output_path}.tsv
`

However when I look at the results, I can see that each of the region has been paired with only 91 other regions whereas the bed file contains 234 region. Do you know how to make it look at all possible pairs ?

Thanks a lot, 
Best,

**Comment by Lucas446** [comment] 2024-01-22 22:54
Sorry actually it is fine, the regions I input are spread among different chromosomes and I see that hicmaptools look at intra-chr interaction only not inter-chr, 

I think that is it, 

Best

**Comment by jmchangTW** [comment] 2024-01-24 08:46
Dear Lucas,

I suppose the issue is resolved since I received the following reply from you.
If no other issue, I will close the issue.

---
Sorry actually it is fine, the regions I input are spread among different chromosomes and I see that hicmaptools look at intra-chr interaction only not inter-chr,

I think that is it,

Best
---

**Comment by Lucas446** [comment] 2024-01-24 19:44
Hi Chang, 

Actually, is there a possibility to also output the interaction having 0 contacts when using -sites option ?

thanks a lot, 
Best, 
Tanguy

**Comment by jmchangTW** [comment] 2024-01-28 12:48
Dear Tanguy,

Yes, the HiCmapTools does not print anything if no correlated bin has been found by the following if-else condition.
---
			// output result only there is bin count
			if(sum_bin > 0)
----
Is it fine to output zeros for all metrics?

Best,
Jia-Ming

**Comment by jmchangTW** [comment] 2024-01-28 12:51
Dear Tanguy,

I mean zero for metrics sum_*, rand_*,  divide_*, and rank_*.
https://hicmaptools.readthedocs.io/en/latest/format.html#output

Best,
Jia-Ming

**Comment by jmchangTW** [comment] 2024-02-02 13:05
Dear Tanguy,

I have revised HiCmapTools, which will output zeros when 0 contacts happen.

Best,
Jia-Ming

**Closed as completed by jmchangTW** 2024-02-02 13:05 UTC
